version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: daily
      time: '03:00'
    target-branch: main
    labels:
      - dependabot
    open-pull-requests-limit: 20
    ignore:
      - dependency-name: 'node'
        versions: ['22.x']
    groups:
      vite:
        patterns:
          - 'vite'
          - 'vite-plugin-*'
      vitest:
        patterns:
          - '@vitest/*'
          - 'vitest'
      eslint:
        patterns:
          - '@eslint/js'
          - 'eslint'
          - 'eslint-plugin-*'
      playwright:
        patterns:
          - '@playwright/test'
          - 'playwright-bdd'
      prettier:
        patterns:
          - 'prettier'
          - 'prettier-plugin-*'
          - 'eslint-config-prettier'
      typescript:
        patterns:
          - 'typescript'
          - 'typescript-eslint'
    commit-message:
      prefix: BAU
  - package-ecosystem: docker
    directory: '/'
    schedule:
      interval: daily
      time: '03:00'
    target-branch: main
    labels:
      - dependabot
    commit-message:
      prefix: BAU
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    target-branch: main
    labels:
      - dependabot
    commit-message:
      prefix: BAU
