sonar.projectKey=govuk-one-login_ipv-cri-ob-front
sonar.organization=govuk-one-login
sonar.sources=src
sonar.exclusions=src/assets/**/*,src/types/**/*

sonar.tests=test
sonar.test.exclusions=test/browser/**/*

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=src/assets/**/*,src/config/**/*,src/locales/**/*,src/utils/dev-tooling/**/*,src/index.ts,src/utils/logger.ts
