export * as checkDetailsController from './check-details.controller'
export * as chooseBankController from './choose-bank.controller'
export * as consentController from './consent.controller'
export * as proveAnotherWayController from './prove-another-way.controller'
export * as selectSignInMethodController from './select-sign-in-method.controller'
export * as startController from './start.controller'
