name: Build and deploy

on:
  workflow_call:
    secrets:
      role_arn:
        required: true
      artifact_bucket:
        required: true
      container_sign_kms_key:
        required: true
      ecr_repository:
        required: true
      ecr_repository_tests:
        required: true
      dynatrace_paas_token:
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  app-image-build-and-push:
    name: Build and push app image
    runs-on: ubuntu-latest
    steps:
      - name: Push to ECR and upload SAM template to S3
        uses: govuk-one-login/devplatform-upload-action-ecr@v1.5.0
        with:
          private-docker-registry: khw46367.live.dynatrace.com
          private-docker-login-username: khw46367
          private-docker-login-password: ${{ secrets.dynatrace_paas_token }}
          artifact-bucket-name: ${{ secrets.artifact_bucket }}
          container-sign-kms-key-arn: ${{ secrets.container_sign_kms_key }}
          template-file: deploy/template.yml
          role-to-assume-arn: ${{ secrets.role_arn }}
          ecr-repo-name: ${{ secrets.ecr_repository }}

  test-image-build-and-push:
    name: Build and push test image
    runs-on: ubuntu-latest
    steps:
      - uses: govuk-one-login/devplatform-upload-action-ecr@v1.5.0
        with:
          role-to-assume-arn: ${{ secrets.role_arn }}
          build-and-push-image-only: true
          artifact-bucket-name: ''
          ecr-repo-name: ${{ secrets.ecr_repository_tests }}
          dockerfile: test/browser/smoke.Dockerfile
          push-latest-tag: true
          container-sign-kms-key-arn: ${{ secrets.container_sign_kms_key }}
