name: Post merge

on:
  push:
    branches:
      - main

jobs:
  sonar-scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0 # required for sonar
      - name: Setup Node
        uses: ./.github/actions/node-setup
      - name: Unit tests
        run: npm run test
      - name: Sonar scan
        uses: SonarSource/sonarqube-scan-action@v7.0.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  deploy-dev:
    uses: ./.github/workflows/_deploy.yml
    secrets:
      role_arn: ${{ secrets.DEV_GH_ACTIONS_ROLE_ARN }}
      artifact_bucket: ${{ secrets.DEV_ARTIFACT_BUCKET }}
      container_sign_kms_key: ${{ secrets.DEV_CONTAINER_SIGN_KMS_KEY }}
      ecr_repository: ${{ secrets.DEV_ECR_REPOSITORY }}
      dynatrace_paas_token: ${{ secrets.DYNATRACE_PAAS_TOKEN }}

  deploy-build:
    uses: ./.github/workflows/_deploy.yml
    secrets:
      role_arn: ${{ secrets.BUILD_GH_ACTIONS_ROLE_ARN }}
      artifact_bucket: ${{ secrets.BUILD_ARTIFACT_BUCKET }}
      container_sign_kms_key: ${{ secrets.BUILD_CONTAINER_SIGN_KMS_KEY }}
      ecr_repository: ${{ secrets.BUILD_ECR_REPOSITORY }}
      dynatrace_paas_token: ${{ secrets.DYNATRACE_PAAS_TOKEN }}
