name: Post merge

on:
  push:
    branches:
      - main

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Setup Node
        uses: govuk-one-login/github-actions/node/install-dependencies@4c76410195b5fcb1804fc7c183ed20704252830f
        with:
          node-version-file: '.nvmrc'
      - name: Unit tests
        run: npm run test
      - name: Upload coverage report
        uses: actions/upload-artifact@v7
        with:
          name: coverage
          path: coverage/
          retention-days: 1

  sonar-scan:
    runs-on: ubuntu-latest
    needs: unit-tests
    permissions:
      contents: read
    steps:
      - name: Run SonarCloud scan
        uses: govuk-one-login/github-actions/code-quality/sonarcloud@9d6ee027d0b9167dfc25e67124951956278bb585
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          sonar-token: ${{ secrets.SONAR_TOKEN }}
          coverage-artifact: coverage
          coverage-run-id: ${{ github.run_id }}

  deploy-dev:
    uses: ./.github/workflows/_deploy.yml
    permissions:
      id-token: write
      contents: read
    secrets:
      role_arn: ${{ secrets.DEV_GH_ACTIONS_ROLE_ARN }}
      artifact_bucket: ${{ secrets.DEV_ARTIFACT_BUCKET }}
      container_sign_kms_key: ${{ secrets.DEV_CONTAINER_SIGN_KMS_KEY }}
      ecr_repository: ${{ secrets.DEV_ECR_REPOSITORY }}
      ecr_repository_tests: ${{ secrets.DEV_ECR_TESTS_REPOSITORY }}
      dynatrace_paas_token: ${{ secrets.DYNATRACE_PAAS_TOKEN }}

  deploy-build:
    uses: ./.github/workflows/_deploy.yml
    permissions:
      id-token: write
      contents: read
    secrets:
      role_arn: ${{ secrets.BUILD_GH_ACTIONS_ROLE_ARN }}
      artifact_bucket: ${{ secrets.BUILD_ARTIFACT_BUCKET }}
      container_sign_kms_key: ${{ secrets.BUILD_CONTAINER_SIGN_KMS_KEY }}
      ecr_repository: ${{ secrets.BUILD_ECR_REPOSITORY }}
      ecr_repository_tests: ${{ secrets.BUILD_ECR_TESTS_REPOSITORY }}
      dynatrace_paas_token: ${{ secrets.DYNATRACE_PAAS_TOKEN }}
