name: PR check

on:
  pull_request:
    types:
      - opened
      - reopened
      - ready_for_review
      - synchronize

jobs:
  static-checks:
    permissions:
      contents: read
    uses: ./.github/workflows/static-checks.yml
    with:
      ts-used: true

  unit-tests:
    permissions:
      contents: read
    needs: static-checks
    uses: ./.github/workflows/unit-tests-coverage.yml
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  browser-tests:
    permissions:
      contents: read
    needs:
      - unit-tests
    uses: ./.github/workflows/browser-tests.yml
    with:
      playwright-used: true

  merge-status:
    runs-on: ubuntu-latest
    needs: [static-checks, unit-tests, browser-tests]
    if: always()
    steps:
      - run: |
          failed=()
          [[ "${{ needs.static-checks.result }}" != "success" ]] && failed+=("static-checks")
          [[ "${{ needs.unit-tests.result }}" != "success" ]] && failed+=("unit-tests")
          [[ "${{ needs.browser-tests.result }}" != "success" ]] && failed+=("browser-tests")

          if [[ ${#failed[@]} -gt 0 ]]; then
            echo "The following jobs failed: ${failed[*]}"
            exit 1
          fi
